### ISSUE TITLE
lunrIndexer: this.builder.pipeline.register is not a function

### ISSUE THREAD

**Issue by maesapasap** [TheIdentitySelector/thiss-mdq#101]
thiss-mdq fails to run with `lunr` indexer because of a bug

[This function](https://github.com/TheIdentitySelector/thiss-mdq/blob/4899d9306e2f3a18d678ced60fbbb80d374a5d37/search-index.js#L16) does not exist in the version of lunr.js used. It should be replaced with the static function `lunr.Pipeline.registerFunction`. See https://lunrjs.com/docs/lunr.Pipeline.html.

**Comment by maesapasap** [comment]
Also, is adding and registering it actually necessary? I tried removing them, and didn't see any issues.

**Comment by enriquepablo** [comment]
It is recommendable to use the new `fuse` indexer, it offers much better performance
